"""Cross-instance federation for SyncBot.

Re-exports public API from :mod:`federation.core` and
:mod:`federation.api` so callers can use ``import federation``
and access all federation functions directly.
"""

from federation.core import (
    FEDERATION_USER_AGENT,
    delete_pairing_code,
    encode_federation_connection_blob,
    federation_endpoint_url,
    federation_sign,
    federation_verify,
    generate_federation_code,
    get_instance_id,
    get_or_create_instance,
    get_or_create_instance_keypair,
    get_public_url,
    initiate_federation_connect,
    instance_id_matches_public_key,
    parse_federation_code,
    public_key_fingerprint,
    push_allowed_workspaces,
    push_delete,
    push_edit,
    push_message,
    push_reaction,
    push_teams,
    push_users,
    refresh_federation_allowlists,
    refresh_instance,
    sign_body,
    this_primary_team_id,
    this_primary_workspace_name,
    validate_webhook_url,
    verify_body,
)
from federation.deliver import deliver_remote, federation_image_payloads

__all__ = [
    "FEDERATION_USER_AGENT",
    "deliver_remote",
    "delete_pairing_code",
    "encode_federation_connection_blob",
    "federation_endpoint_url",
    "federation_image_payloads",
    "federation_sign",
    "federation_verify",
    "generate_federation_code",
    "get_instance_id",
    "get_or_create_instance",
    "get_or_create_instance_keypair",
    "get_public_url",
    "this_primary_team_id",
    "this_primary_workspace_name",
    "initiate_federation_connect",
    "instance_id_matches_public_key",
    "parse_federation_code",
    "public_key_fingerprint",
    "push_delete",
    "push_edit",
    "push_message",
    "push_reaction",
    "push_allowed_workspaces",
    "push_teams",
    "push_users",
    "refresh_federation_allowlists",
    "refresh_instance",
    "sign_body",
    "validate_webhook_url",
    "verify_body",
]
